//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI.NET.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AI.NET.Resources.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Current Chat 的本地化字符串。
        /// </summary>
        public static string DeleteChat {
            get {
                return ResourceManager.GetString("DeleteChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please set your AI in the Settings first! 的本地化字符串。
        /// </summary>
        public static string ExAINotSet {
            get {
                return ResourceManager.GetString("ExAINotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No sys prompt selected. Go to sys prompt and set one, then choose it in the ListBox. 的本地化字符串。
        /// </summary>
        public static string ExNoSysPromptSelection {
            get {
                return ResourceManager.GetString("ExNoSysPromptSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No topic selected. Please create a new chat first. 的本地化字符串。
        /// </summary>
        public static string ExNoTopicSelection {
            get {
                return ResourceManager.GetString("ExNoTopicSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An unexpected error occurred. Calm down, it&apos;s not your fault. We&apos;ve saved the information to the logs subfolder in your app folder, please create a new bug report issue on GitHub with the logs. Do you want to go there now? 的本地化字符串。
        /// </summary>
        public static string ExUnexpected {
            get {
                return ResourceManager.GetString("ExUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error restoring window position 的本地化字符串。
        /// </summary>
        public static string ExWindowPosition {
            get {
                return ResourceManager.GetString("ExWindowPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully update README.md 的本地化字符串。
        /// </summary>
        public static string InfoReadmeUpdated {
            get {
                return ResourceManager.GetString("InfoReadmeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updating README.md... 的本地化字符串。
        /// </summary>
        public static string InfoReadmeUpdating {
            get {
                return ResourceManager.GetString("InfoReadmeUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings saved and applied! 的本地化字符串。
        /// </summary>
        public static string InfoSettingSaved {
            get {
                return ResourceManager.GetString("InfoSettingSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mem0 Server URL 的本地化字符串。
        /// </summary>
        public static string Mem0ServerUrl {
            get {
                return ResourceManager.GetString("Mem0ServerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Chat 的本地化字符串。
        /// </summary>
        public static string NewChat {
            get {
                return ResourceManager.GetString("NewChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenAI Api Key 的本地化字符串。
        /// </summary>
        public static string OpenAIApiKey {
            get {
                return ResourceManager.GetString("OpenAIApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenAI Base URL 的本地化字符串。
        /// </summary>
        public static string OpenAIBaseUrl {
            get {
                return ResourceManager.GetString("OpenAIBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenAI Model 的本地化字符串。
        /// </summary>
        public static string OpenAIModel {
            get {
                return ResourceManager.GetString("OpenAIModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send Message 的本地化字符串。
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Prompt 的本地化字符串。
        /// </summary>
        public static string SystemPrompt {
            get {
                return ResourceManager.GetString("SystemPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input your prompt, double click to edit 的本地化字符串。
        /// </summary>
        public static string SystemPromptInstruction {
            get {
                return ResourceManager.GetString("SystemPromptInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Mem0 的本地化字符串。
        /// </summary>
        public static string UseMem0 {
            get {
                return ResourceManager.GetString("UseMem0", resourceCulture);
            }
        }
    }
}
